name = "LeanCA"
version = "0.2.0"
defaultTargets = ["LeanCA"]

[[lean_lib]]
name = "LeanCA"
roots = ["ToMathlib", "ComplexAnalysis"]
globs = [
  "ToMathlib", "ToMathlib.+",
  "ComplexAnalysis", "ComplexAnalysis.+",
]

[[lean_exe]]
name = "main"
root = "LeanCA"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc2"
