/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import ComplexAnalysis.Runge.OpenSet
public import ComplexAnalysis.Cycle.ArgumentPrinciple
public import Mathlib.Analysis.Complex.LocallyUniformLimit

/-!
# The Mittag-Leffler theorem

Let `U` be open, `S ⊆ U` a set without accumulation points in `U`, and for each `a ∈ S` let
`P a` be a function holomorphic off `a` (a principal part). There is a function `f` holomorphic
on `U \ S` such that near every `a ∈ S` the difference `f - P a` extends holomorphically.

The proof follows Conway VIII.3.2: with the exhaustion of `U` by the hole-free hulls
`rungeHull U n (1 / (n + 1))`, the finitely many principal parts with poles in the `n`-th ring
are corrected by rational functions with poles outside `U` (Runge's theorem) so that the
corrections are bounded by `2⁻ⁿ` on the previous hull; the corrected series converges locally
uniformly on `U` minus the poles.

## Main results

* `Complex.mittagLeffler`: existence of a meromorphic function with prescribed principal parts.
* `Complex.compl_mem_codiscreteWithin_iff`, `Complex.mittagLeffler_of_forall_le_dist`: the
  hypothesis `Sᶜ ∈ codiscreteWithin U` as an explicit metric condition, and the theorem in
  that form.
* `Complex.differentiableOn_of_mem_adjoin_rungeGenerators`: rational functions with poles
  outside `U` are holomorphic on `U`.

## References

* J. B. Conway, *Functions of One Complex Variable I*, second edition, Springer, 1978
  (background on one-variable holomorphic functions).
-/

public noncomputable section

open Set Metric Filter Function
open scoped Topology

namespace Complex

/-- Elements of the algebra generated by the identity and the simple poles at points outside
`U` are holomorphic on `U`. -/
theorem differentiableOn_of_mem_adjoin_rungeGenerators {U : Set ℂ} {r : ℂ → ℂ}
    (hr : r ∈ Algebra.adjoin ℂ (rungeGenerators Uᶜ)) : DifferentiableOn ℂ r U := by
  induction hr using Algebra.adjoin_induction with
  | mem g hg =>
    rcases hg with rfl | ⟨a, ha, rfl⟩
    · exact differentiableOn_id
    · exact ((differentiableOn_const a).sub differentiableOn_id).inv fun z hz ↦
        sub_ne_zero.mpr fun h ↦ ha ((show a = z from h).symm ▸ hz)
  | algebraMap c => exact differentiableOn_const _
  | add x y _ _ hx hy => exact hx.add hy
  | mul x y _ _ hx hy => exact hx.mul hy

/-- The `n`-th hole-free hull of the standard exhaustion of `U`. -/
def mlHull (U : Set ℂ) (n : ℕ) : Set ℂ := rungeHull U n (1 / (n + 1))

/-- The compact sets used in the Mittag–Leffler exhaustion increase with their index. -/
theorem mlHull_mono {U : Set ℂ} {m n : ℕ} (h : m ≤ n) : mlHull U m ⊆ mlHull U n :=
  rungeHull_mono (by exact_mod_cast h)
    (one_div_le_one_div_of_le (by positivity) (by exact_mod_cast Nat.add_le_add_right h 1))

/-- Each set in the Mittag–Leffler exhaustion is compact. -/
theorem isCompact_mlHull (U : Set ℂ) (n : ℕ) : IsCompact (mlHull U n) :=
  isCompact_rungeHull U n _

/-- Each set in the Mittag–Leffler exhaustion is contained in the original set. -/
theorem mlHull_subset {U : Set ℂ} (n : ℕ) : mlHull U n ⊆ U :=
  rungeHull_subset (by positivity)

/-- Each hull lies in the interior of the next one. -/
theorem mlHull_subset_interior (U : Set ℂ) (n : ℕ) :
    mlHull U n ⊆ interior (mlHull U (n + 1)) := by
  intro z hz
  rw [mem_interior_iff_mem_nhds]
  set ρ : ℝ := 1 / ((n + 1) * (n + 2)) with hρ_def
  have hρ : 0 < ρ := by positivity
  have hρ1 : ρ ≤ 1 := by
    rw [hρ_def, div_le_one (by positivity)]
    nlinarith
  have hkey : (1 : ℝ) / (n + 1) - ρ = 1 / (n + 2) := by
    rw [hρ_def]
    field_simp
    ring
  filter_upwards [ball_mem_nhds z hρ] with z' hz'
  rw [mem_ball, dist_eq_norm] at hz'
  refine Set.mem_inter ?_ fun u hu ↦ ?_
  · rw [mem_closedBall, dist_zero_right]
    have h1 : ‖z‖ ≤ n := by simpa using hz.1
    have h2 : ‖z'‖ ≤ ‖z‖ + ‖z' - z‖ := norm_le_norm_add_norm_sub' z' z
    push_cast
    linarith
  · have h1 := hz.2 u hu
    have h2 : dist z u ≤ dist z z' + dist z' u := dist_triangle z z' u
    have h3 : dist z z' = ‖z' - z‖ := by rw [dist_eq_norm, norm_sub_rev]
    have h4 : (1 : ℝ) / ((n + 1 : ℕ) + 1) = 1 / (n + 2) := by push_cast; ring
    rw [h4]
    linarith

/-- Every point of `U` lies in some hull. -/
theorem exists_mem_mlHull {U : Set ℂ} (hU : IsOpen U) {z : ℂ} (hz : z ∈ U) :
    ∃ n, z ∈ mlHull U n := by
  obtain ⟨m, hm⟩ := exists_forall_subset_rungeHull_nat hU isCompact_singleton
    (singleton_subset_iff.mpr hz)
  exact ⟨m, hm m le_rfl (mem_singleton z)⟩

/-- A series of holomorphic functions is holomorphic when a summable uniform bound
holds after finitely many initial terms. -/
private theorem differentiableOn_tsum_of_tail_bound (s : ℕ → ℂ → ℂ) {V : Set ℂ}
    (hV : IsOpen V) (hdiff : ∀ n, DifferentiableOn ℂ (s n) V)
    {u : ℕ → ℝ} (hu : Summable u) (m : ℕ)
    (hbound : ∀ n z, z ∈ V → m ≤ n → ‖s n z‖ ≤ u n) :
    DifferentiableOn ℂ (fun z ↦ ∑' n, s n z) V := by
  have hsum : ∀ z ∈ V, Summable fun n ↦ s n z := fun z hz ↦
    hu.of_norm_bounded_eventually <| by
      rw [Nat.cofinite_eq_atTop]
      filter_upwards [eventually_ge_atTop m] with n hn using hbound n z hz hn
  have htail : DifferentiableOn ℂ (fun z ↦ ∑' n, s (n + m) z) V :=
    Complex.differentiableOn_tsum_of_summable_norm (u := fun n ↦ u (n + m))
      (hu.comp_injective (add_left_injective m)) (fun n ↦ hdiff (n + m)) hV
      fun n z hz ↦ hbound (n + m) z hz (by omega)
  have hhead : DifferentiableOn ℂ (fun z ↦ ∑ n ∈ Finset.range m, s n z) V :=
    .fun_sum fun n _ ↦ hdiff n
  exact (hhead.add htail).congr fun z hz ↦ ((hsum z hz).sum_add_tsum_nat_add m).symm

/-- Removing from an open set `U` any subset of a set `S` without accumulation points in `U`
leaves an open set. -/
private theorem isOpen_sdiff_of_subset {U S T : Set ℂ} (hU : IsOpen U)
    (hS : Sᶜ ∈ codiscreteWithin U) (hTS : T ⊆ S) : IsOpen (U \ T) := by
  rw [isOpen_iff_mem_nhds]
  rintro z ⟨hzU, hzT⟩
  rw [mem_codiscreteWithin] at hS
  filter_upwards [eventually_nhdsWithin_iff.mp (disjoint_principal_right.mp (hS z hzU)),
    hU.mem_nhds hzU] with w hw hwU
  refine ⟨hwU, fun hwT ↦ ?_⟩
  by_cases hwz : w = z
  · exact hzT (hwz ▸ hwT)
  · exact hw hwz ⟨hwU, fun h ↦ h (hTS hwT)⟩

/-- A finite sum of principal parts is holomorphic off its poles. -/
private theorem differentiableOn_sum_principalParts {S : Set ℂ} {P : ℂ → ℂ → ℂ}
    (hP : ∀ a ∈ S, DifferentiableOn ℂ (P a) {a}ᶜ) {F : Finset ℂ} (hF : (F : Set ℂ) ⊆ S) :
    DifferentiableOn ℂ (fun z ↦ ∑ a ∈ F, P a z) (F : Set ℂ)ᶜ :=
  .fun_sum fun a ha ↦ (hP a (hF ha)).mono fun z hz h ↦ hz (by
    rw [Set.mem_singleton_iff.mp h]; exact ha)

/-- A relatively discrete set is partitioned into finite layers according to the first
compact exhaustion set containing each point. -/
private theorem exists_mittagLeffler_layers {U S : Set ℂ} (hU : IsOpen U)
    (hSU : S ⊆ U) (hS : Sᶜ ∈ codiscreteWithin U) :
    ∃ T : ℕ → Finset ℂ,
      (∀ n, (T n : Set ℂ) ⊆ S) ∧
      (∀ n a, a ∈ T n → ∀ m < n, a ∉ mlHull U m) ∧
      (∀ {m n}, m ≠ n → ∀ a, a ∈ T m → a ∉ T n) ∧
      (∀ a ∈ S, ∃ m, a ∈ T m ∧ a ∈ mlHull U m) := by
  classical
  have hfin : ∀ n, (mlHull U n ∩ S).Finite := fun n ↦ by
    simpa [Set.sdiff_compl] using (isCompact_mlHull U n).finite_sdiff_of_mem_codiscreteWithin
      (codiscreteWithin_mono (mlHull_subset n) hS)
  set Tset : ℕ → Set ℂ := fun n ↦ {a | a ∈ mlHull U n ∧ a ∈ S ∧ ∀ m < n, a ∉ mlHull U m}
  have hTfin : ∀ n, (Tset n).Finite := fun n ↦ (hfin n).subset fun a ha ↦ ⟨ha.1, ha.2.1⟩
  set T : ℕ → Finset ℂ := fun n ↦ (hTfin n).toFinset
  have hTmem : ∀ n a, a ∈ T n ↔ a ∈ mlHull U n ∧ a ∈ S ∧ ∀ m < n, a ∉ mlHull U m :=
    fun n a ↦ Set.Finite.mem_toFinset _
  have hTK : ∀ n a, a ∈ T n → ∀ m < n, a ∉ mlHull U m := fun n a ha ↦ ((hTmem n a).mp ha).2.2
  refine ⟨T, fun n a ha ↦ ((hTmem n a).mp ha).2.1, hTK, ?_, fun a ha ↦ ?_⟩
  · intro m n hmn a ham han
    rcases lt_or_gt_of_ne hmn with h | h
    · exact hTK n a han m h ((hTmem m a).mp ham).1
    · exact hTK m a ham n h ((hTmem n a).mp han).1
  · have hex : ∃ n, a ∈ mlHull U n := exists_mem_mlHull hU (hSU ha)
    exact ⟨Nat.find hex, (hTmem _ a).mpr ⟨Nat.find_spec hex, ha, fun k hk ↦ Nat.find_min hex hk⟩,
      Nat.find_spec hex⟩

/-- **The corrected terms of the Mittag-Leffler series.** The principal parts are grouped into
finite layers `T n`, and the `n`-th layer is corrected by a rational function `r n` with poles
outside `U` (Runge's theorem) so that the corrected term is at most `2⁻ⁿ` on the earlier
hulls. -/
private theorem exists_mittagLeffler_terms {U S : Set ℂ} (hU : IsOpen U) (hSU : S ⊆ U)
    (hS : Sᶜ ∈ codiscreteWithin U) {P : ℂ → ℂ → ℂ}
    (hP : ∀ a ∈ S, DifferentiableOn ℂ (P a) {a}ᶜ) :
    ∃ (T : ℕ → Finset ℂ) (r : ℕ → ℂ → ℂ),
      (∀ n, (T n : Set ℂ) ⊆ S) ∧ (∀ {m n}, m ≠ n → ∀ a, a ∈ T m → a ∉ T n) ∧
      (∀ a ∈ S, ∃ m, a ∈ T m ∧ a ∈ mlHull U m) ∧ (∀ n, DifferentiableOn ℂ (r n) U) ∧
      ∀ m n z, z ∈ mlHull U m → m + 1 ≤ n →
        ‖∑ a ∈ T n, P a z - r n z‖ ≤ (1 / 2 : ℝ) ^ n := by
  obtain ⟨T, hTS, hTK, hTdisj, hTcover⟩ := exists_mittagLeffler_layers hU hSU hS
  have hcorr : ∀ n, ∃ r ∈ Algebra.adjoin ℂ (rungeGenerators Uᶜ),
      ∀ z ∈ mlHull U n, ‖∑ a ∈ T (n + 1), P a z - r z‖ ≤ (1 / 2 : ℝ) ^ (n + 1) := fun n ↦
    runge (isCompact_mlHull U n)
      (disjoint_left.mpr fun a (ha : a ∈ Uᶜ) haK ↦ ha (mlHull_subset n haK))
      (fun w hw hb ↦ exists_compl_mem_connectedComponentIn_rungeHull hw hb)
      (T (n + 1)).finite_toSet.isClosed.isOpen_compl
      (fun z hz hzT ↦ hTK (n + 1) z hzT n (Nat.lt_succ_self n) hz)
      (differentiableOn_sum_principalParts hP (hTS (n + 1))) _ (by positivity)
  choose r hr hrε using hcorr
  refine ⟨T, fun n ↦ Nat.casesOn n (fun _ ↦ 0) r, hTS, hTdisj, hTcover, fun n ↦ ?_,
    fun m n z hz hmn ↦ ?_⟩
  · cases n with
    | zero => exact differentiableOn_const _
    | succ k => exact differentiableOn_of_mem_adjoin_rungeGenerators (hr k)
  · obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le' (show 1 ≤ n by omega)
    exact hrε k z (mlHull_mono (by omega) hz)

/-- **The Mittag-Leffler theorem.** For a set `S` without accumulation points in the open set
`U` and principal parts `P a` holomorphic off `a`, there is a function holomorphic on `U \ S`
whose difference with `P a` extends holomorphically over each `a ∈ S`. -/
theorem mittagLeffler {U : Set ℂ} (hU : IsOpen U) {S : Set ℂ} (hSU : S ⊆ U)
    (hS : Sᶜ ∈ codiscreteWithin U) {P : ℂ → ℂ → ℂ}
    (hP : ∀ a ∈ S, DifferentiableOn ℂ (P a) {a}ᶜ) :
    ∃ f : ℂ → ℂ, DifferentiableOn ℂ f (U \ S) ∧
      ∀ a ∈ S, ∃ g : ℂ → ℂ, AnalyticAt ℂ g a ∧ f =ᶠ[𝓝[≠] a] fun z ↦ P a z + g z := by
  classical
  obtain ⟨T, r, hTS, hTdisj, hTcover, hr, hbound⟩ := exists_mittagLeffler_terms hU hSU hS hP
  set K : ℕ → Set ℂ := mlHull U
  set t : ℕ → ℂ → ℂ := fun n z ↦ ∑ a ∈ T n, P a z - r n z
  have htdiff : ∀ n, DifferentiableOn ℂ (t n) (U \ (T n : Set ℂ)) := fun n ↦
    ((differentiableOn_sum_principalParts hP (hTS n)).mono fun z hz ↦ hz.2).sub
      ((hr n).mono fun z hz ↦ hz.1)
  have hsummable : ∀ m z, z ∈ K m → Summable fun n ↦ t n z := fun m z hz ↦
    summable_geometric_two.of_norm_bounded_eventually <| by
      rw [Nat.cofinite_eq_atTop]
      filter_upwards [eventually_ge_atTop (m + 1)] with n hn using hbound m n z hz hn
  refine ⟨fun z ↦ ∑' n, t n z, ?_, fun a ha ↦ ?_⟩
  · -- holomorphy off `S`
    intro z hz
    obtain ⟨m, hm⟩ := exists_mem_mlHull hU hz.1
    set V : Set ℂ := interior (K (m + 1)) ∩ (U \ S)
    have hVo : IsOpen V := isOpen_interior.inter (isOpen_sdiff_of_subset hU hS subset_rfl)
    have hzV : z ∈ V := ⟨mlHull_subset_interior U m hm, hz⟩
    have hdiff : ∀ n, DifferentiableOn ℂ (t n) V := fun n ↦
      (htdiff n).mono fun w hw ↦ ⟨hw.2.1, fun h ↦ hw.2.2 (hTS n h)⟩
    exact ((differentiableOn_tsum_of_tail_bound t hVo hdiff summable_geometric_two (m + 1 + 1)
      fun n w hw hn ↦ hbound (m + 1) n w (interior_subset hw.1) hn)
      z hzV).differentiableAt (hVo.mem_nhds hzV) |>.differentiableWithinAt
  -- the principal part at `a ∈ S`
  have haU : a ∈ U := hSU ha
  obtain ⟨m, haT, hamK⟩ := hTcover a ha
  set t' : ℕ → ℂ → ℂ := fun n z ↦ if n = m then 0 else t n z
  refine ⟨fun z ↦ (∑ b ∈ (T m).erase a, P b z - r m z) + ∑' n, t' n z, ?_, ?_⟩
  · -- analyticity of the remainder at `a`
    set V : Set ℂ := interior (K (m + 1)) ∩ (U \ (S \ {a}))
    have hVo : IsOpen V := isOpen_interior.inter (isOpen_sdiff_of_subset hU hS sdiff_subset)
    have haV : a ∈ V := ⟨mlHull_subset_interior U m hamK, haU, fun h ↦ h.2 rfl⟩
    have h1 : DifferentiableOn ℂ (fun z ↦ ∑ b ∈ (T m).erase a, P b z) V :=
      (differentiableOn_sum_principalParts hP
        ((Finset.coe_subset.mpr (Finset.erase_subset a _)).trans (hTS m))).mono
        fun w hw hwT ↦ hw.2.2 ⟨hTS m (Finset.mem_of_mem_erase hwT),
          fun hwa ↦ Finset.ne_of_mem_erase hwT hwa⟩
    have hdiff' : ∀ n, DifferentiableOn ℂ (t' n) V := by
      intro n
      by_cases hn : n = m
      · simp [t', hn]
      · simp only [t', hn, ite_false]
        refine (htdiff n).mono fun w hw ↦ ⟨hw.2.1, fun hwT ↦ hw.2.2 ⟨hTS n hwT, fun hwa ↦
          hTdisj (Ne.symm hn) a haT ((show w = a from hwa) ▸ hwT)⟩⟩
    have h3 := differentiableOn_tsum_of_tail_bound t' hVo hdiff' summable_geometric_two
      (m + 1 + 1) fun n z hz hn ↦ by
        simpa [t', show n ≠ m by omega] using hbound (m + 1) n z (interior_subset hz.1) hn
    exact ((h1.sub ((hr m).mono fun w hw ↦ hw.2.1)).add h3).analyticAt (hVo.mem_nhds haV)
  · -- the germ identity
    filter_upwards [nhdsWithin_le_nhds (hU.mem_nhds haU)] with z hzU
    obtain ⟨k, hk⟩ := exists_mem_mlHull hU hzU
    rw [(hsummable k z hk).tsum_eq_add_tsum_ite m]
    simp only [t, t', ← Finset.add_sum_erase _ _ haT]
    ring

/-- For `S ⊆ U`, the condition `Sᶜ ∈ codiscreteWithin U` says exactly that no point of `U` is
an accumulation point of `S`: every `z ∈ U` has a positive distance from `S \ {z}`. -/
theorem compl_mem_codiscreteWithin_iff {U S : Set ℂ} (hSU : S ⊆ U) :
    Sᶜ ∈ codiscreteWithin U ↔ ∀ z ∈ U, ∃ ε > 0, ∀ w ∈ S, w ≠ z → ε ≤ dist w z := by
  rw [mem_codiscreteWithin]
  refine forall₂_congr fun z _ ↦ ?_
  rw [disjoint_principal_right, Metric.mem_nhdsWithin_iff]
  constructor
  · rintro ⟨ε, hε, h⟩
    refine ⟨ε, hε, fun w hwS hwz ↦ not_lt.mp fun hlt ↦ ?_⟩
    exact h ⟨mem_ball.mpr hlt, hwz⟩ ⟨hSU hwS, not_not.mpr hwS⟩
  · rintro ⟨ε, hε, h⟩
    refine ⟨ε, hε, fun w ⟨hwb, hwz⟩ ⟨_, hwS⟩ ↦ ?_⟩
    exact (h w (not_not.mp hwS) hwz).not_gt (mem_ball.mp hwb)

/-- **The Mittag-Leffler theorem**, with the singularity set described metrically. For a set
`S ⊆ U` with no accumulation point in the open set `U` (every `z ∈ U` has a positive distance
from `S \ {z}`) and principal parts `P a` holomorphic off `a`, there is a function holomorphic on
`U \ S` whose difference with `P a` extends holomorphically over each `a ∈ S`. -/
theorem mittagLeffler_of_forall_le_dist {U : Set ℂ} (hU : IsOpen U) {S : Set ℂ} (hSU : S ⊆ U)
    (hS : ∀ z ∈ U, ∃ ε > 0, ∀ w ∈ S, w ≠ z → ε ≤ dist w z) {P : ℂ → ℂ → ℂ}
    (hP : ∀ a ∈ S, DifferentiableOn ℂ (P a) {a}ᶜ) :
    ∃ f : ℂ → ℂ, DifferentiableOn ℂ f (U \ S) ∧
      ∀ a ∈ S, ∃ g : ℂ → ℂ, AnalyticAt ℂ g a ∧ f =ᶠ[𝓝[≠] a] fun z ↦ P a z + g z :=
  mittagLeffler hU hSU ((compl_mem_codiscreteWithin_iff hSU).mpr hS) hP

end Complex

end
